services:
  db:
    image: mariadb:latest
    container_name: wp_db
    restart: always
    environment:
      MYSQL_DATABASE: wp_blog
      MYSQL_USER: wp_admin
      MYSQL_PASSWORD: Set_A_Strong_Password_Here
      MYSQL_ROOT_PASSWORD: root_password_security
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.3-fpm
    container_name: wp_app
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_admin
      WORDPRESS_DB_PASSWORD: Set_A_Strong_Password_Here
      WORDPRESS_DB_NAME: wp_blog
    volumes:
      - ./blog:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: wp_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html:ro        # Static root
      - ./blog:/var/www/html/blog:ro   # WordPress subfolder
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wordpress

volumes:
  db_data: