version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: wp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.3-fpm
    container_name: wp_app
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./blog:/var/www/html

  nginx:
    depends_on:
      - wordpress
    image: nginx:alpine
    container_name: wp_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./blog:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data:
